### ISSUE TITLE
Missing Font awesome 

### ISSUE THREAD

**Issue by haniali1234** [geekwise-jennifer-tablett/dustybuns#6]
Page: Home page
issue:  missing font awesome
photo: 
![screen shot 2016-03-22 at 4 03 15 pm](https://cloud.githubusercontent.com/assets/11038599/13970713/cad550cc-f047-11e5-94d7-02abd84eeb20.png)

**Comment by geekwise-jennifer-tablett** [comment]
have the icons on index page, still cant see them. looking to see where they are previously targeted

**Comment by haniali1234** [comment]
I can see them but not in the right place.

**Comment by geekwise-jennifer-tablett** [comment]
done

**Comment by haniali1234** [comment]
![screen shot 2016-03-24 at 2 28 04 pm](https://cloud.githubusercontent.com/assets/11038599/14031982/f62d7480-f1cc-11e5-8a98-5eba47e845af.png)

**Comment by geekwise-jennifer-tablett** [comment]
done
