### ISSUE TITLE
input boxes

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-jennifer-tablett/dustybuns#8]
issues: input boxes need to be bigger
pages: catering

how yours looks:
![screen shot 2016-03-23 at 10 15 36 am](https://cloud.githubusercontent.com/assets/7436666/13994123/946579ba-f0e0-11e5-99cb-da24f7808127.png)

how it should look:
![screen shot 2016-03-23 at 10 15 56 am](https://cloud.githubusercontent.com/assets/7436666/13994122/93200598-f0e0-11e5-919b-ea0633080283.png)

options:
add more padding inside input boxes

**Comment by geekwise-jennifer-tablett** [comment]
done, having a hard time with the inner dropdown, any suggestions?
